### ISSUE TITLE
Создать компонент поиск

### ISSUE THREAD

**Issue by truesik** [truesik/Montao#116]
Для начала создать новый компонент Search. В нем должен быть input и кнопка.
Компонент должен располагаться в NavBar по середине не зависимо от того авторизован пользователь или нет.
Инпут и кнопка должны располагаться по горизонтали.
Ну и бутстрэпом его чтобы красиво.

**Comment by GeorgeSemenov** [comment]
Поиск центруется на для всех экранов одинаково, для больших - он сползает в бок.

**Comment by GeorgeSemenov** [comment]
Проблемы: Поиск не влезает между хедером и кнопками sign-in  и log-in
                        При разделении ширины экрана между div header и div collapse последний не влезает.                        
                        При маленьких экранах поиск не втискивается между хедером и пызанстолом.

**Comment by GeorgeSemenov** [comment]
Чекай гугл плей и другие сайты, для динамичной ширины поиска.

**Comment by GeorgeSemenov** [comment]
Почему див.хедер не находится в колапсбаре (хотя тот занимает весь бар почти) надо побаловаться с jsfiddle.
