### ISSUE TITLE
Написать action

### ISSUE THREAD

**Issue by truesik** [truesik/Montao#124]
Создать новый файл SearchActions.js.
В файле создать функцию, по аналогии с другими скриптами, с именем search.
На вход функции идет запрос (query).
Запрос делается по адресу ".../api/search?q=myCommunityTitle", где myCommunityTitle - имя сообщества, которое должно вернутся в результатах (пока ищем по полному имени).

Также замутить новый файл с константами, в нем создать три записи (SEARCH_REQUEST, SEARCH_SUCCESS, SEARCH_FAILURE), в общем как в других файлах.

**Comment by GeorgeSemenov** [comment]
ну т.е. внутри серча будет момент где вызывается SEARCH_REQUEST, потом начинается fetch, который долбиться по какому то адресу, приходит ответ, если все хорошо то SEARCH_SUCCESS, если не хорошо то FAILUREОтправлено:ПнОт:Рысцов Вячеславв общем по аналогии
