### ISSUE TITLE
ChannelDAOJpa

### ISSUE THREAD

**Issue by truesik** [truesik/Montao#154]
Реализовать ChannelDAO интерфейс используя JPA.
Для аналогии использовать UserDAOJpa и интернет.

**Comment by GeorgeSemenov** [comment]
Разберёшься с Ченнелом, делай другие.
Но перед этим посмотри, какие Слава новые методы понапихал в котлине, стоит их взять на вооружение.

**Comment by GeorgeSemenov** [comment]
Изучи морфологическую шляпу для монтао : https://habrahabr.ru/company/everydaytools/blog/320964/
https://docs.google.com/spreadsheets/d/1k5sTdMpWKvPIqUi1UNIKQ8xBpw5DEyRfwnAQxZoHmDw/edit#gid=874147518
Изучи уже сделанный функционал, подумай о будущем.
