### ISSUE TITLE
Сверстать страницу приветствия

### ISSUE THREAD

**Issue by GeorgeSemenov** [truesik/Montao#18]
Сверстать страницу приветствия в соответствие с мокапами.

**Comment by GeorgeSemenov** [comment]
Приделай строку поиска и добавь сообщества для всех типов пользователей.

**Comment by GeorgeSemenov** [comment]
Не забудь про кнопку для поиска , в мокапе её нет , ещё ты хотел использовать фонт-афигеть!

**Comment by GeorgeSemenov** [comment]
Нужно прикрутить выплывающую строку , когда нажимаешь на лупу в мобильном режиме.

**Comment by GeorgeSemenov** [comment]
Не забудь переделать окошко регистрации аккаунта , оно не влезает в мобильную версию. Возможно стоит поставить надписи поверх input'ов.

**Comment by GeorgeSemenov** [comment]
В мобильной версии сайта нужно переставить знаки  с лева на право должны быть : кнопка войти , логотип сообщества , кнопка поиска.

**Comment by GeorgeSemenov** [comment]
Надобно рефакторить код , убери в стилях для #popup-window margin-left 150 px можно обойтись и без него.

**Comment by GeorgeSemenov** [comment]
Бэк в мобильной версии должен вписываться в размеры дисплея , тоже самое касается и остальных размеров (планшет и монитор)

**Comment by GeorgeSemenov** [comment]
Хорошо бы дополнить ReadMe.md доп информацией  
    Установка — тут описаны все шаги, как запустить проект, чтобы даже «дизайнер» мог это сделать;
    Запуск — примеры базовых команд для запуска проекта;
    Опции запуска — список всех возможных параметров и их описание;
    «Первые шаги» — собственно, это и есть нужный раздел:
        быстрый поиск UI-блока — описание инструмента для препарирования приложения;
        «Что? Где? Когда?» — краткое описание структуры проекта;
        создание UI-блока — минимальная информация, как создать UI-блок;
        «Логика приложения, или где искать обработку событий?»;
    Примеры/скринкасты — экспериментальный раздел с примерами.
См. пример тут https://habrastorage.org/files/30a/f2b/40c/30af2b40cd564035bbdf253dd961f21b.png

**Comment by truesik** [comment]
Гош, ты лучше создавай новое задание, если оно никак не связано с данным. Это к написанию ридми.

**Comment by GeorgeSemenov** [comment]
Приделай плавно выпадающее меню к аватарке.

**Comment by GeorgeSemenov** [comment]
Не забудь выложить сайт на сервер и показать посонам. И как тебе удаётся находить такие места , где интернета или нет , или он настолько слабый , что ты не можешь залить файлы на сервер ?

**Comment by GeorgeSemenov** [comment]
Есть какое-то серьёзное разхождение между рендерингом аватара в огнелисе и хроме . Вначале я думал что дело в top и left , но детальный разбор показал , что именно свойство float : right. Отображается по кривому. Надо разобраться.

**Comment by GeorgeSemenov** [comment]
Хорошо , вроде кроссбарузерность сделана , но ты забыл про скрипты! Проверь все скрипты , которые только можешь во всех трёх браузерах. Скрипт pop-up-search уже работает неверно. Подправь.

**Comment by GeorgeSemenov** [comment]
В выпадающем меню.
Выход
Настройки
Новые сообщества
Профиль.
Убери имя аватарки , только оставь саму аватарку , не приветствуй никого.

**Comment by GeorgeSemenov** [comment]
Попробуй сделать анимацию #popup-menu более плавной , пока что она "шершавая".

**Comment by GeorgeSemenov** [comment]
Приделай ротацию стрелочки выпадающего меню.

**Comment by GeorgeSemenov** [comment]
Изучи react И посмотри что Слава запушил.

**Comment by GeorgeSemenov** [comment]
Изучи, как работает монтао, от корки до корки.
